config/routes.rb
Rails.application.routes.draw do
  resources :parcels
  
  resources :office_visits

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  root to: 'home#index'

  resources :patients do
    collection do
      get 'graph'
      get 'validation'
    end
  end

  patch 'validate', to: 'patients#validate'

  resources :forms do
    collection do 
      get 'export'
      post 'export'
    end
  end

  get 'graphs/index'
  post 'graphs/index'
  
  get 'pdf/generate_pdf'
end

app/models/parcel.rb
class Parcel < ApplicationRecord
	belongs_to :office_visit

	validates_presence_of :value
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_parcel, only: [:edit, :update, :destroy]
  before_action :set_office_visit, only: [:index, :create]


  def index
    @parcels = @office_visit.parcels.paginate(page: params[:page], per_page: 5)

    @parcel = Parcel.new


    if params[:page].present? && params[:page] > "1"
      @count = (params[:page].to_i - 1) * 5
    else
      @count = 0
    end
  end

  def create
    @parcel = Parcel.new(parcel_params)
    @parcel.office_visit = @office_visit

    if @parcel.save
      redirect_to request.referrer, notice: 'Parcela criada com sucesso!'
    else
      redirect_to request.referrer, notice: 'Erro ao salvar parcela.'
    end
  end


  def destroy
    @parcel.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Parcela excluída com sucesso!' }
      format.json { head :no_content }
    end
  end

  private

    def set_office_visit
      @office_visit = OfficeVisit.find(params[:office])
    end

    def set_parcel
      @parcel = Parcel.find(params[:id])
    end


    def parcel_params
      params.require(:parcel).permit(:value, :observation)
    end
end

app/helpers/parcels_helper.rb
module ParcelsHelper
end

app/views/parcels/_form.html.erb
<%= form_for(parcel, url: {office: params[:office]}) do |f| %>
  <% if parcel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parcel.errors.count, "error") %> prohibited this parcel from being saved:</h2>

      <ul>
      <% parcel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    Valor Recebido <br />
    <%= f.number_field :value, step: :any, placeholder: 'R$ 100,00', class: 'form-control', required: true %>
  </div>

  <div class="field form-group">
    Observação <br />
    <%= f.text_area :observation, class: 'form-control' %>
  </div>

  <div class="actions mb-4">
    <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  </div>


  <%= link_to 'Voltar', office_visits_path(id_patient: params[:id_patient]), class: 'btn btn-warning mb-4' %>
<% end %>

app/views/parcels/index.html.erb
<h3>Adicionar Parcela do Pagamento</h3>

Paciente: <b><%= @office_visit.patient.name %></b>

<section class="row text-center">
  <section class="col-md-4">

    <hr />
      Valor a receber: <b style="color: red"><%= @office_visit.value %></b>
    <hr />
      Valor recebido: <b style="color: green"><%= @parcels.sum(:value) %></b>
    <hr />
    <%= render 'form', parcel: @parcel %>
  </section>

  <section class="col-md-8 mt-3">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Id</th>
          <th>Valor Recebido</th>
          <th>Data de recebimento</th>
          <th>Observação</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% if @parcels.count > 0 %>
          <% @parcels.each do |parcel| %>
            <% content_tag :div do %>
              <%= @count += 1 %>
            <% end %>

            <tr>
              <td><%= @count %></td>
              <td><%= parcel.value %></td>
              <td><%= parcel.created_at %></td>
              <td><%= parcel.observation %></td>
              <td><%= link_to 'Apagar', parcel, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger' %></td>
            </tr>
          <% end %>
        <% else %>
          <td colspan="5">Não existem gastos cadastrados ainda.</td>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @parcels %>
  </section>
</section> 