config/routes.rb
Rails.application.routes.draw do
  resources :parcels
  
  resources :office_visits

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  root to: 'home#index'

  resources :patients do
    collection do
      get 'graph'
      get 'validation'
    end
  end

  patch 'validate', to: 'patients#validate'

  resources :forms do
    collection do 
      get 'export'
      post 'export'
    end
  end

  get 'graphs/index'
  post 'graphs/index'
  
  get 'pdf/generate_pdf'
end

app/models/office_visit.rb
class OfficeVisit < ApplicationRecord
  belongs_to :patient
  has_many :parcels

  validates :value, :hour, :date, presence: false

  mount_uploaders :documents, DocumentUploader
end

app/controllers/office_visits_controller.rb
class OfficeVisitsController < ApplicationController
  before_action :set_office_visit, only: [:show, :edit, :update, :destroy]
  before_action :set_patient, only: [:index, :edit, :new, :create]


  def index
    @office_visits = @patient.office_visits
                      .order(date: :ASC, hour: :ASC)
                      .paginate(page: params[:page], per_page: 10)
  end


  def show
  end


  def new
    @office_visit = OfficeVisit.new
    show_calendar
  end

  def edit
    show_calendar
  end

  def create
    @office_visit = OfficeVisit.new(office_visit_params)
    @office_visit.patient = @patient

    if @office_visit.save
      redirect_to request.referrer, notice: 'Consulta criada com sucesso!'
    else
      redirect_to request.referrer, notice: 'Erro na criação da consulta.'
    end
  end


  def update
    if @office_visit.update(office_visit_params)
      redirect_to office_visits_path(id_patient: params[:id_patient]), notice: 'Consulta atualizada com sucesso.'
    else
      redirect_to office_visits_path(id_patient: params[:id_patient]), notice: 'Erro na atualização da consulta.'
    end
  end


  def destroy
    @office_visit.destroy
    redirect_to request.referrer, notice: 'Consulta cancelada com sucesso!'
  end

  private

    def show_calendar
      @patients_per_day = OfficeVisit.joins(:patient).where("patients.user_id = ?", current_user.id).order(hour: :ASC).group_by(&:date)
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
    end

    def set_patient
      @patient = Patient.find(params[:id_patient])
    end

    def set_office_visit
      @office_visit = OfficeVisit.find(params[:id])
    end


    def office_visit_params
      params.require(:office_visit).permit(:patient_id, :value, :date, :hour, :description, {documents: []})
    end
end

app/helpers/office_visits_helper.rb
module OfficeVisitsHelper
end

app/views/office_visits/_form.html.erb
<%= form_with(model: office_visit, local: true, class: 'col-md-4 offset-md-4') do |form| %>
  
  <p>
    Paciente: <b><%= @patient.name %></b>
  </p>

  <%= hidden_field_tag :id_patient, params[:id_patient] %>

  <div class="field form-group m-4">
    <%= form.label :valor_cobrado %>
    <%= form.number_field :value, step: :any, min: 0, placeholder: 'R$ 100,00', class: 'form-control' %>
  </div>

  <div class="field form-group m-4">
    <%= form.label :descrição %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="field form-group m-4">
      <%= form.label :anexos %> <br />
      <%= form.file_field :documents, multiple: true, class: 'form-control' %>
    </div>

  <div class="actions">
    <%= form.submit 'Salvar', class: 'btn btn-info' %>
  </div>

  <%= link_to 'Voltar', :back, class: 'btn btn-warning m-4' %>
<% end %>

app/views/office_visits/_register.html.erb
<%= form_with(model: office_visit, local: true) do |form| %>
  
  <p>
    Paciente: <b><%= @patient.name %></b>
  </p>

  <%= hidden_field_tag :id_patient, params[:id_patient] %>
  
  <section class="row">
    <section class="form-group col-md-4">
        <section class="row date_div">
          <%= form.text_field :date, type: 'date', required: true, class: 'form-control col-6' %>
          <%= form.text_field :hour, type: 'time', required: true, class: 'form-control col-6' %>
        </section>

        <div class="actions mt-4 mb-4">
          <%= form.submit 'Salvar', class: 'btn btn-info' %>
        </div>

        <% if params[:register].present? %>
          <%= link_to 'Voltar', patients_path, class: 'btn btn-warning' %>
        <% else %>
          <%= link_to 'Voltar', office_visits_path(id_patient: params[:id_patient]), class: 'btn btn-warning' %>
        <% end %>
    </section>

    <section class="calendar col-md-8">
      <%= render 'calendar/show' %>
    </section>
  </section>
<% end %>

app/views/office_visits/edit.html.erb
<section class="text-center">
	<h1>Editar Atendimento</h1>

	<% if params[:remark].present? %>
		<%= render 'register', office_visit: @office_visit %>
	<% else %>
		<%= render 'form', office_visit: @office_visit %>
	<% end %>
</section>

app/views/office_visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listagem de Consultas</h1>

<p>
  Paciente: <b><%= @patient.name %></b>
</p>

<table class="table table-hover text-center">
  <thead>
    <tr>
      <th>Data da consulta</th>
      <th>Descrição</th>
      <th>Anexos</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @office_visits.each do |office_visit| %>
      <tr>
        <td><%= (office_visit.date.present?) ? office_visit.date : '-' %> <%= (office_visit.hour.present?) ? office_visit.hour : '-' %></td>
        <td><p><%= (office_visit.description.present?) ? truncate(office_visit.description, :length => 20, separator: ' ') : '-' %></p></td>
        <td>
          <% office_visit.documents.each_with_index do |document, index| %>
            <%= link_to("Anexo #{index + 1} ", document.url, target: '_blank') %>
            <br />
          <% end %>
        </td>
        <td><%= link_to 'Remarcar Paciente', edit_office_visit_path(office_visit, id_patient: @patient, remark: true), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Preencher Atendimento', edit_office_visit_path(office_visit, id_patient: @patient), class: 'btn btn-success' %></td>
        <td><%= link_to 'Pagamento', parcels_path(office: office_visit, id_patient: params[:id_patient]), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Exibir', office_visit, class: 'btn btn-info' %></td>
        <td><%= link_to 'Cancelar', office_visit, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @office_visits %>

<br>

<%= link_to 'Voltar', patients_path, class: 'btn btn-warning mt-4' %>

app/views/office_visits/new.html.erb
<section class="text-center">
	<h1>Nova Consulta</h1>

	<% if params[:register].present? %>
		<%= render 'register', office_visit: @office_visit %>
	<% else %>
		<%= render 'form', office_visit: @office_visit %>
	<% end %>
</section>

app/views/office_visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<% @office_visit.documents.each_with_index do |document, index| %>
	  <%= link_to("Anexo #{index + 1} ", document.url, target: '_blank', class: 'btn btn-info m-2') %>
	<% end %>
</p>	

<section class="text-center show_div">
	<p>
	  <strong>Paciente:</strong>
	  <%= @office_visit.patient.name %>
	</p>

	<p>
	  <strong>Data da Consulta:</strong>
	  <%= @office_visit.date %> <%= @office_visit.hour %>
	</p>

	<p>
	  <strong>Descrição:</strong>
	  <%= @office_visit.description %>
	</p>

	<%= link_to 'Voltar', :back, class: 'btn btn-warning' %>
</section>