config/routes.rb
Rails.application.routes.draw do
  resources :parcels
  
  resources :office_visits

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  root to: 'home#index'

  resources :patients do
    collection do
      get 'graph'
      get 'validation'
    end
  end

  patch 'validate', to: 'patients#validate'

  resources :forms do
    collection do 
      get 'export'
      post 'export'
    end
  end

  get 'graphs/index'
  post 'graphs/index'
  
  get 'pdf/generate_pdf'
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer>
  <!-- Footer Links -->
  <div class="text-center text-md-left mt-5 footer-up">

    <!-- Grid row -->
    <div class="row mt-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold">Elephant RH</h6>
        <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Aqui você gerencia seus pacientes e tem um maior controle sobre os dados!</p>
        <p>Mais seguro, mais rápido, mais <b>Elephant RH!</b></p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-6 col-lg-4 col-xl-4 mx-auto mb-4 text-center">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Links</h6>
        <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <%= link_to 'Home', root_path, class: 'nav_li' %>
        </p>

        <p>
          <%= link_to 'Perfil', edit_user_registration_path, class: 'nav_li' %>
        </p>

        <p>
          <%= link_to 'Clientes', patients_path, class: 'nav_li' %>
        </p>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contato</h6>
        <hr class="mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <%= fa_icon "home" %> Campos dos Goytacazes - RJ
        </p>

        <p>
          <%= fa_icon "envelope" %> elephantrhapp@gmail.com
        </p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
    © 2020 Copyright: Elephant RH
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-icon"></span>
    <span class="navbar-icon"></span>
    <span class="navbar-icon"></span>
  </button>

  <table id="navbarNav">
    <tbody>
      <tr class="navbar-nav text-center">
        <td class="nav-item col">
          <%= link_to 'Home', root_path, class: 'nav_li' %>
        </td>

        <td class="nav-item col">
          <%= link_to 'Perfil', edit_user_registration_path, class: 'nav_li' %>
        </td>

        <td class="nav-item col">
          <%= link_to 'Clientes', patients_path, class: 'nav_li' %>
        </td>

        <% if current_user.category == 'Autônomo' %>
          <td class="nav-item col">
            <%= button_to 'Pagamentos', graphs_index_path, class: 'nav_li' %>
          </td>
        <% end %>

        <td class="nav-item col">
          <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => "nav_li"  %>
        </td>
      </tr>
    </tbody>
  </table>
</nav>