config/routes.rb
Rails.application.routes.draw do
  resources :parcels
  
  resources :office_visits

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  root to: 'home#index'

  resources :patients do
    collection do
      get 'graph'
      get 'validation'
    end
  end

  patch 'validate', to: 'patients#validate'

  resources :forms do
    collection do 
      get 'export'
      post 'export'
    end
  end

  get 'graphs/index'
  post 'graphs/index'
  
  get 'pdf/generate_pdf'
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_one :form, dependent: :destroy
  
  has_many :office_visits

  validates_presence_of :company, :marital_status, :name, :schooling, :age, :office
  
  validates :code, :avatar, presence: false

  mount_uploader :avatar, AvatarUploader


  def validate_code(code)
  	if self.code == code
  		return true
  	end
  end
  
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
  def index
    if params[:search].present?
      @patients = current_user.patient.order(name: :ASC).
        where("lower(name) LIKE :search OR lower(company) LIKE :search
        OR lower(marital_status) LIKE :search OR lower(schooling) LIKE :search
        OR lower(office) LIKE :search", search: "%#{params[:search].downcase}%").paginate(page: params[:page], per_page: 10)
    else
      @patients = current_user.patient.order(name: :ASC).paginate(page: params[:page], per_page: 10)
    end
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.user_id = current_user.id

    if @patient.save
      redirect_to form_new_path(patient_id: @patient.id), notice: 'Candidato Salvo com sucesso!'
    else
      redirect_to patient_index_path, alert: 'Erro ao cadastrar Candidato'
    end
  end

  def graph
    @patient_individual = Patient.find(params[:patient_id])
    @patient_graph = @patient_individual.form.psicological_concepts

    @patient_concept_sum = @patient_individual.form.psicological_concepts.sum
  end

  def edit
    @patient = Patient.find(params[:patient_id])
  end

  def update
    @patient = Patient.find(params[:patient_id])

    if @patient.update(patient_params)
      redirect_to patient_index_path, notice: 'Candidato Atualizado com sucesso!'
    else
      redirect_to patient_index_path, alert: 'Erro na atualização do Candidato!'
    end
  end

  def show
  end

  def destroy
    @patient = Patient.find(params[:id])

    if @patient.destroy
      redirect_to patient_index_path, notice: 'Cliente removido com sucesso!'
    else
      redirect_to patient_index_path, alert: 'Erro na remoção do cliente!'
    end
  end


  private

  def patient_params
    params.require(:patient).permit(:company, :marital_status, :name, :schooling, :age, :office, :avatar)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:edit, :update, :destroy, :graph, :validation]

  def index
    if params[:search].present?
      @patients = current_user.patients.order(name: :ASC).
        where("lower(name) LIKE :search OR lower(company) LIKE :search
        OR lower(marital_status) LIKE :search OR lower(schooling) LIKE :search
        OR lower(office) LIKE :search", search: "%#{params[:search].downcase}%").paginate(page: params[:page], per_page: 10)
    else
      @patients = current_user.patients.order(name: :ASC).paginate(page: params[:page], per_page: 10)
    end
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.user_id = current_user.id

    if @patient.save
      redirect_to patients_path, notice: 'Candidato Salvo com sucesso!'
    else
      redirect_to patients_path, alert: 'Erro ao cadastrar Candidato'
    end
  end

  def graph
    @patient_graph = @patient.form.psicological_concepts

    @patient_concept_sum = @patient.form.psicological_concepts.sum
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to patients_path, notice: 'Candidato Atualizado com sucesso!'
    else
      redirect_to patients_path, alert: 'Erro na atualização do Candidato!'
    end
  end

  def validation
  end

  def validate 
    @patient = Patient.find(params[:id_patient])

    if @patient.validate_code(params[:patient][:code].to_i)
      redirect_to office_visits_path(id_patient: @patient), notice: 'Autenticação realizada!'
    else
      redirect_to request.referrer, alert: 'Senha Inválida!'
    end
  end


  def destroy
    if @patient.destroy
      redirect_to patients_path, notice: 'Cliente removido com sucesso!'
    else
      redirect_to patients_path, alert: 'Erro na remoção do cliente!'
    end
  end


  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:company, :marital_status, :name, :schooling, :age, :office, :code, :avatar)
  end
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/patient/edit.html.erb
<section class="new_patient text-center">
    <h4>Edição de um Cliente</h4>

    <%= form_with(model: @patient, url: {action: 'update', patient_id: params[:patient_id]}, :method => :POST) do |f| %>
      <section class="card">
        <section class="card-header">
          Identificação do Candidato
        </section>

        <section class="card-body">
          <section class="row">
            <section class="col-6">
              Empresa <br />
              <%= f.text_field :company, value: @patient.company  %>
            </section>

            <section class="col-6">
              Estado Civil* <br />
              <%= f.text_field :marital_status, value: @patient.marital_status %>
            </section>

            <section class="col-6">
              Nome do Candidato* <br />
              <%= f.text_field :name, value: @patient.name %>
            </section>

            <section class="col-6">
              Escolaridade* <br />
              <%= f.text_field :schooling, value: @patient.schooling %>
            </section>

            <section class="col-6">
              Idade* <br />
              <%= f.number_field :age, min: 0, value: @patient.age %>
            </section>

            <section class="col-6">
              Cargo <br />
              <%= f.text_field :office, value: @patient.office %>
            </section>
          </section>


          <section class="inferior-buttons">
            <%= f.file_field :avatar, class: 'photo' %>
            <br />
            <%= f.submit 'Salvar', class: 'btn btn-primary save' %>
            <br />
            <br />
            <%= link_to 'Voltar', :back, class: 'btn btn-warning save' %>
          </section>
        </section>
      </section>
    <% end %>
</section>

app/views/patient/graph.html.erb
<section class="new_patient text-center">
    <h4>Gráfico de conceito psicológico</h4>

    <hr />

    <b>Candidato:</b> <%= @patient_individual.name %> <br />
    <b>Soma Total do Conceito:</b> <%= @patient_concept_sum %>

    <hr />

    <canvas id="myChart"></canvas>

    <%= javascript_tag do %>
      var ctx = document.getElementById('myChart').getContext('2d');

      var data = {
        labels: ["Dinamismo", "Comunicação", "Trabalho em Equipe", "Relacionamento",
        "Organização", "Adaptação", "Trabalho sob pressão", "Proatividade",
        "Iniciativa"],
        datasets: [{
          <% if @patient_concept_sum > 19 %>
            backgroundColor: "rgba(10,200,10,0.3)",
          <% else %>
            backgroundColor: "rgba(200,10,10,0.3)",
          <% end %>
          data: <%= @patient_graph %>
        }]
      };

      options = {
        scale: {
            angleLines: {
                display: false
            },
            ticks: {
                suggestedMin: 0,
                suggestedMax: 3
            }
        }
      };


      var myRadarChart = new Chart(ctx, {
        type: 'radar',
        data: data,
        options: options
      });
    <% end %>

    <br />
    <%= link_to 'Voltar', patient_index_path, class: 'btn btn-warning' %>
</section>

app/views/patient/index.html.erb
<section class="patient text-center">
  <h3>Listagem de todos os candidatos cadastrados <%= fa_icon "user-circle" %></h3>

  <%= form_tag(patient_index_path, method: :get, class: "form-group")  do %>
      <section class="row">
        <%= text_field_tag :search, params[:search], class: "form-control text_form col-md-10 ml-2", placeholder: 'Busque por algum candidato!' %>
        <%= submit_tag ("Procurar"), class: "form-control button_form col-md-1 ml-2" %>
      </section>
      <small>O campo de busca procura por Nome, Empresa, Estado Civil, Escolaridade, Cargo </small>
  <% end %>

  <% @patients.each do |patient| %>
    <section class="card patients-list">
      <section class="row">
        <section class="col-md-2">
          <% if patient.avatar.url.present? %>
            <%= image_tag(patient.avatar.medium.url) %>
          <% end %>
        </section>

        <section class="col-md-8 pt-3">
          <h3><%= patient.name %></h3>

          <% if patient.form.present? %>
            <p><%= truncate(patient.form.personal_moment, :length => 50, separator: ' ') %></p>
            <section class="row">
              <%= link_to 'Visualizar PDF', form_export_path(patient_id: patient, format: :pdf), class: 'col-lg-3', target: "_blank" %>
              <%= link_to 'Editar Formulário', form_edit_path(patient_id: patient.form.id), class: 'col-lg-2' %>
              <%= link_to 'Editar Perfil', patient_edit_path(patient_id: patient), class: 'col-lg-2' %>
              <%= link_to 'Gráfico', patient_graph_path(patient_id: patient), class: 'col-lg-2' %>
            </section>
          <% else %>
            <section class="row">
              <%= link_to 'Preencher Formulário', form_new_path(patient_id: patient.id), class: 'col-md-5' %>
              <%= link_to 'Editar Perfil', patient_edit_path(patient_id: patient), class: 'col-md-5' %>
            </section>
          <% end %>

        </section>

        <section class="col-md-2 pt-4 mt-4">
          <%= link_to '<i class="fa fa-trash"></i>'.html_safe, {action: :destroy, id: patient.id}, data: { confirm: 'Tem certeza?' }, title: 'Excluir', class: 'delete' %>
        </section>
      </section>
    </section>
  <% end %>

  <br />

  <%= will_paginate @patients %>
</section>

app/views/patient/show.html.erb
<section class="new_patient text-center">
    <h4>Edição de um Cliente</h4>

    <%= form_with(model: @patient, url: {action: 'update', patient_id: params[:patient_id]}) do |f| %>
      <section class="card">
        <section class="card-header">
          Identificação do Candidato
        </section>

        <section class="card-body">
          <section class="row">
            <section class="col-6">
              Empresa <br />
              <%= f.text_field :company, value: @patient.company  %>
            </section>

            <section class="col-6">
              Estado Civil* <br />
              <%= f.text_field :marital_status, value: @patient.marital_status %>
            </section>

            <section class="col-6">
              Nome do Candidato* <br />
              <%= f.text_field :name, value: @patient.name %>
            </section>

            <section class="col-6">
              Escolaridade* <br />
              <%= f.text_field :schooling, value: @patient.schooling %>
            </section>

            <section class="col-6">
              Idade* <br />
              <%= f.number_field :age, min: 0, value: @patient.age %>
            </section>

            <section class="col-6">
              Cargo <br />
              <%= f.text_field :office, value: @patient.office %>
            </section>
          </section>


          <section class="inferior-buttons">
            <%= f.file_field :avatar, class: 'photo' %>
            <br />
            <%= f.submit 'Salvar', class: 'btn btn-primary save' %>
            <br />
            <br />
            <%= link_to 'Voltar', patient_index_path, class: 'btn btn-warning save' %>
          </section>
        </section>
      </section>
    <% end %>
</section>